@startuml
"User" as User
"Usuario cadastrado Agente" as AgenteUserLoged
"Usuario cadastrado Cliente" as ClientUserLoged
"Sistema" as System
"Banco Agente" as BancoAgente

"Cadastra" as (Cadastro)
"Esolhe tipo Usuario" as (UserType)
"Introduzir Pedidos" as (introPedi)
"Modificar Pedidos" as (modPedi)
"Consultar Pedidos" as (consulPed)
"Cancelar Pedidos" as (cancelPed)
"Analisar Pedidos do ponto de vista financeiro" as (avalPed)
"Adiciona consideracao" as (addConcideracao)
"Armazenar dados contrates" as (armazenDataContratantes)
"Armazenar dados veiculo" as (armazenDataVeiculo)
"Verifica tipo contrato" as (verificaTipoContrato)
"Vincula veiculo a um dono" as (vinculaVeiculoDono)
"Conceder contrato de credito" as (contratoCredito)

User --> (Cadastro)
ClientUserLoged --> (introPedi)
ClientUserLoged --> (modPedi)
ClientUserLoged --> (consulPed)
ClientUserLoged --> (cancelPed)

AgenteUserLoged --> (modPedi)
AgenteUserLoged --> (avalPed)

System --> (armazenDataContratantes)
System --> (armazenDataVeiculo)
System --> (verificaTipoContrato)

BancoAgente --> (contratoCredito)
Cadastro .> (UserType) : includes
(avalPed) .> (addConcideracao) : extends
(verificaTipoContrato) .> (vinculaVeiculoDono) : extends
@enduml