git @startuml
"User" as User
"Agente" as Agente
"Cliente" as Cliente
"Agente" as Agente

"Cadastra" as (Cadastro)
"Esolhe tipo Usuario" as (UserType)
"Introduzir Pedidos" as (introPedi)
"Modificar Pedidos" as (modPedi)
"Consultar Pedidos" as (consulPed)
"Cancelar Pedidos" as (cancelPed)
"Analisar Pedidos do ponto de vista financeiro" as (avalPed)
"Adiciona consideracao" as (addConcideracao)
"Conceder contrato de credito" as (contratoCredito)

User --> (Cadastro)
Cliente --> (introPedi)
Cliente --> (modPedi)
Cliente --> (consulPed)
Cliente --> (cancelPed)

Agente --> (modPedi)
Agente --> (avalPed)

Agente --> (contratoCredito)
Cadastro .> (UserType) : includes
(avalPed) .> (addConcideracao) : extends
@enduml