@startuml
skinparam classAttributeIconSize 0

package "Autenticador" #DDDDDD {

class Usuario{
-id:int
-login:String
-senha:String
-role:Role

+login(login: String, senha: String): String
}

enum Role{
    CLIENTE
    AGENTE
}

Usuario -- Role
}

class Agente{
- id:int
- usuario: Usuario

+modificarPedido(idPedido: int, pedido: Pedido): Pedido
+avaliarPedido(idPedido: int, status: StatusPedido): Pedido
}

class Cliente{
 -id:int
 -nome:String
 -RG:String
 -CPF:String
 -usuario:Usuario
 -profissao:Profissao
 -endereco:Endereco
 -rendimentosAuferidos: List<double>

 +cadastrar(cliente: Cliente): Cliente
 +introduzirPedido(idCliente: int, idAutomovel: int): Pedido
 +modificarPedido(idPedido: int, pedido: Pedido): Pedido
 +consultarPedido(idPedido: int): Pedido
 +cancelarPedido(idPedido: int): void
}

class Endereco{
-id:int
-CEP:String
-numero:int
-complemento:String
}

class Profissao{
-id:int
-cargo:String
-empresa:String
-salario:double
}

class Automovel{
-id:int
-matricula:String
-ano:String
-marca:String
-modelo:String
-placa:String
-proprietario: String
-disponivel: boolean

+alterarDono(novoProprietario: String): Automovel
+verificarDisponibilidade(): boolean
}

class Contrato{
-id:int
-valor:double
-pedido:Pedido
}

class Pedido{
-id:int
-data: Date
-automovel:Automovel
-cliente:Cliente
-agente:Agente
-status:StatusPedido

+alterarStatus(status: StatusPedido): Pedido
}

enum StatusPedido{
    APROVADO
    PENDENTE
    CANCELADO
}


Pedido -- Cliente
Pedido -- Automovel
Pedido -- Contrato
Pedido -- Agente
Pedido -- StatusPedido

Cliente -- Usuario
Cliente -- Profissao
Cliente *- Endereco

@enduml