@startuml
skinparam classAttributeIconSize 0

'package "Autenticador" #DDDDDD {
'
'class Usuario{
'-id:int
'-login:String
'-senha:String
'-role:Role
'
'+login(login: String, senha: String): String
'}
'
'enum Role{
'    CLIENTE
'    EMPRESA
'    BANCO
'}

'Usuario -- Role
'}

class Usuario{
-id:int
-login:String
-senha:String
-role:Role
}

class Agente{
}

class Banco{
}

class Cliente{
 -id:int
 -nome:String
 -RG:String
 -CPF:String
 -usuario:Usuario
 -profissao:Profissao
 -endereco:Endereco
 -rendimentosAuferidos: List<double>

 +cadastrar(cliente: Cliente): Cliente
}

class Endereco{
-id:int
-CEP:String
-numero:int
-complemento:String
}

class Profissao{
-id:int
-cargo:String
-empresa: Empresa
-salario:double
}

class Empresa{
-id:int
-nome:String
}

class Automovel{
-id:int
-matricula:String
-ano:String
-marca:String
-modelo:String
-placa:String
-proprietario: String
-disponivel: boolean

+vincularProprietario(novoProprietario: String): Automovel
+alterarDisponibilidade(disponivel: bololean): void
+verificarDisponibilidade(): boolean
}

class Contrato{
-id:int
-valor:double
-pedido:Pedido

+gerarContrato(contrato: Contrato): Contrato
}

class Pedido{
-id:int
-data: Date
-automovel:Automovel
-cliente:Cliente
-status:StatusPedido

+modificarPedido(idPedido: int, pedido: Pedido): Pedido
+consultarPedido(idPedido: int): Pedido
+cancelarPedido(idPedido: int): void
+avaliarPedido(idPedido: int, status: StatusPedido): Pedido
}

enum StatusPedido{
    APROVADO
    PENDENTE
    CANCELADO
}
Pedido -- Cliente
Pedido -- Automovel
Pedido -- Contrato
Pedido -- StatusPedido

Usuario <-- Cliente
Usuario <-- Agente
Agente <-- Banco

Cliente -- Profissao
Cliente *- Endereco

Profissao -- Empresa

@enduml